/*5. Extend or Create a NumberChecker utility class and perform the following task. Call
from the main() method the different methods and display results. Make sure all are static
methods
Hint =>
a. Method to Check if a number is a prime number. A prime number is a number greater
than 1 that has no positive divisors other than 1 and itself.
b. Method to Check if a number is a neon number. A neon number is a number where
the sum of digits of the square of the number is equal to the number itself
c. Method to Check if a number is a spy number. A number is called a spy number if the
sum of its digits is equal to the product of its digits
d. Method to Check if a number is an automorphic number. An automorphic number is a
number whose square ends with the number itself. E.g. 5 is an automorphic number
e. Method to Check if a number is a buzz number. A buzz number is a number that is
either divisible by 7 or ends with 7*/using System;internal static class NumberChecker04{    public static void Main()    {        Console.Write("Enter Number: ");        int number = int.Parse(Console.ReadLine());        bool isPrime = IsPrime(number);        Console.WriteLine($"{number} is a Prime Number: {isPrime}");        bool isNeon = IsNeonNumber(number);        Console.WriteLine($"{number} is a Neon Number: {isNeon}");        bool isSpy = IsSpyNumber(number);        Console.WriteLine($"{number} is a Spy Number: {isSpy}");        bool isAutomorphic = IsAutomorphicNumber(number);        Console.WriteLine($"{number} is an Automorphic Number: {isAutomorphic}");        bool isBuzz = IsBuzzNumber(number);        Console.WriteLine($"{number} is a Buzz Number: {isBuzz}");    }    public static bool IsPrime(int number)    {        if (number <= 1) return false;        for (int i = 2; i <= Math.Sqrt(number); i++)        {            if (number % i == 0) return false;        }        return true;    }    public static bool IsNeonNumber(int number)    {        int square = number * number;        int sumOfDigits = 0;        while (square > 0)        {            sumOfDigits += square % 10;            square /= 10;        }        return sumOfDigits == number;    }      public static bool IsSpyNumber(int number)    {        int sum = 0;        int product = 1;        while (number > 0)        {            int digit = number % 10;            sum += digit;            product *= digit;            number /= 10;        }        return sum == product;    }    public static bool IsAutomorphicNumber(int number)    {        int square = number * number;        string numberStr = number.ToString();        string squareStr = square.ToString();        return squareStr.EndsWith(numberStr);    }    public static bool IsBuzzNumber(int number)    {        return number % 7 == 0 || number % 10 == 7;    }    }